# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Assignment\数字图像处理课程设计\代码\ui\AboutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(404, 242)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        AboutDialog.setFont(font)
        AboutDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.confirmBtn = QtWidgets.QPushButton(AboutDialog)
        self.confirmBtn.setObjectName("confirmBtn")
        self.verticalLayout.addWidget(self.confirmBtn)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "关于"))
        self.label.setText(_translate("AboutDialog", "Minecraft动物检测系统"))
        self.label_2.setText(_translate("AboutDialog", "作者：杨子琪"))
        self.label_3.setText(_translate("AboutDialog", "版本：1.0"))
        self.label_4.setText(_translate("AboutDialog", "时间：2025/1/3"))
        self.confirmBtn.setText(_translate("AboutDialog", "确定"))
