# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Assignment\数字图像处理课程设计\代码\ui\LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(282, 142)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        LoginDialog.setFont(font)
        LoginDialog.setWhatsThis("")
        LoginDialog.setModal(True)
        self.loginBtn = QtWidgets.QPushButton(LoginDialog)
        self.loginBtn.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.loginBtn.setObjectName("loginBtn")
        self.accountEdit = QtWidgets.QLineEdit(LoginDialog)
        self.accountEdit.setGeometry(QtCore.QRect(80, 27, 171, 20))
        self.accountEdit.setObjectName("accountEdit")
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(30, 33, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 63, 54, 12))
        self.label_2.setObjectName("label_2")
        self.passwordEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwordEdit.setGeometry(QtCore.QRect(80, 60, 171, 20))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.registerBtn = QtWidgets.QPushButton(LoginDialog)
        self.registerBtn.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.registerBtn.setObjectName("registerBtn")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "登录"))
        self.loginBtn.setText(_translate("LoginDialog", "登录"))
        self.label.setText(_translate("LoginDialog", "用户名"))
        self.label_2.setText(_translate("LoginDialog", "密码"))
        self.registerBtn.setText(_translate("LoginDialog", "注册..."))
