# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Assignment\数字图像处理课程设计\代码\ui\RegisterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(292, 177)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        RegisterDialog.setFont(font)
        RegisterDialog.setModal(True)
        self.accountEdit = QtWidgets.QLineEdit(RegisterDialog)
        self.accountEdit.setGeometry(QtCore.QRect(80, 34, 171, 20))
        self.accountEdit.setObjectName("accountEdit")
        self.passwordEdit = QtWidgets.QLineEdit(RegisterDialog)
        self.passwordEdit.setGeometry(QtCore.QRect(80, 67, 171, 20))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.label = QtWidgets.QLabel(RegisterDialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(RegisterDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RegisterDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 54, 12))
        self.label_3.setObjectName("label_3")
        self.passwordConfirmEdit = QtWidgets.QLineEdit(RegisterDialog)
        self.passwordConfirmEdit.setGeometry(QtCore.QRect(80, 97, 171, 20))
        self.passwordConfirmEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordConfirmEdit.setObjectName("passwordConfirmEdit")
        self.registerBtn = QtWidgets.QPushButton(RegisterDialog)
        self.registerBtn.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.registerBtn.setObjectName("registerBtn")

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "注册"))
        self.label.setText(_translate("RegisterDialog", "用户名"))
        self.label_2.setText(_translate("RegisterDialog", "密码"))
        self.label_3.setText(_translate("RegisterDialog", "确认密码"))
        self.registerBtn.setText(_translate("RegisterDialog", "注册"))
